# Generated by Django 3.1.3 on 2021-01-26 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20210126_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_phone_number', users.models.CustomPhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('shipping_street_address_1', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_street_address_2', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_town_or_city', models.CharField(blank=True, default='', max_length=40)),
                ('shipping_county', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('shipping_country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('billing_full_name', models.CharField(blank=True, default='', max_length=50)),
                ('billing_phone_number', users.models.CustomPhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('billing_street_address_1', models.CharField(blank=True, default='', max_length=80)),
                ('billing_street_address_2', models.CharField(blank=True, default='', max_length=80)),
                ('billing_town_or_city', models.CharField(blank=True, default='', max_length=40)),
                ('billing_county', models.CharField(blank=True, default='', max_length=80)),
                ('billing_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('billing_country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('liked_products', models.ManyToManyField(blank=True, related_name='users', through='users.Liked', to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liked',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
