# Generated by Django 3.1.9 on 2021-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210422_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='billing_county',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_postcode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_street_address_2',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_county',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_street_address_2',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
