# Generated by Django 3.1.8 on 2021-05-04 14:20

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100, null=True)),
                ('name_it', models.CharField(default='', max_length=100, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('content_en', tinymce.models.HTMLField(null=True)),
                ('content_it', tinymce.models.HTMLField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='a', editable=False, max_length=100)),
                ('slug_en', models.SlugField(default='a', editable=False, max_length=100, null=True)),
                ('slug_it', models.SlugField(default='a', editable=False, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
    ]
