# Generated by Django 3.1.8 on 2021-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='active_cookie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='active_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
