# Generated by Django 3.1.8 on 2021-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_auto_20210511_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='active_terms',
            field=models.BooleanField(default=False),
        ),
    ]
