# Generated by Django 3.1.8 on 2021-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policy_active_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='active_returns',
            field=models.BooleanField(default=False),
        ),
    ]
