# Generated by Django 3.1.3 on 2020-12-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20201204_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'ordering': ['email_address'], 'verbose_name': 'Email Histories'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['name']},
        ),
    ]
