# Generated by Django 3.1.3 on 2020-12-07 23:32

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20201204_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email_list',
            new_name='email_list_en',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email_list_it',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None),
        ),
    ]
