# Generated by Django 3.1.3 on 2020-12-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20201207_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailhistory',
            old_name='newsletter',
            new_name='newsletter_en',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='newsletter_it',
            field=models.BooleanField(default=False),
        ),
    ]
