# Generated by Django 3.1.3 on 2020-12-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20201208_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'ordering': ['email_address'], 'verbose_name': 'Email Historie'},
        ),
    ]
