# Generated by Django 3.1.3 on 2021-04-21 18:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0009_auto_20210327_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_full_name', models.CharField(max_length=50)),
                ('shipping_phone_number', users.models.CustomPhoneNumberField(max_length=128, region=None)),
                ('shipping_street_address_1', models.CharField(max_length=80)),
                ('shipping_street_address_2', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_town_or_city', models.CharField(max_length=40)),
                ('shipping_county', models.CharField(blank=True, max_length=80)),
                ('shipping_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_full_name', models.CharField(max_length=50)),
                ('billing_phone_number', users.models.CustomPhoneNumberField(max_length=128, region=None)),
                ('billing_street_address_1', models.CharField(max_length=80)),
                ('billing_street_address_2', models.CharField(blank=True, default='', max_length=80)),
                ('billing_town_or_city', models.CharField(max_length=40)),
                ('billing_county', models.CharField(blank=True, default='', max_length=80)),
                ('billing_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_cart', models.TextField()),
                ('stripe_pid', models.CharField(max_length=254)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
