# Generated by Django 3.1.9 on 2021-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210607_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_county',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_address_2',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street_address_2',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
