# Generated by Django 3.1.3 on 2020-11-26 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='carousel')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
