# Generated by Django 3.1.3 on 2020-11-27 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='info')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
