# Generated by Django 3.1.3 on 2020-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_homeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
