# Generated by Django 3.1.3 on 2020-11-27 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20201127_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
    ]
