# Generated by Django 3.1.3 on 2020-12-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20201128_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='description_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='description_it',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='name_it',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
