# Generated by Django 3.1.3 on 2020-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20201207_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='button_text_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='button_text_it',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='name_it',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_it',
            field=models.TextField(null=True),
        ),
    ]
