# Generated by Django 3.1.3 on 2020-12-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_review_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeInfo',
            new_name='Category',
        ),
    ]
