# Generated by Django 3.1.3 on 2020-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_detailinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='description1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='description1_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='description2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='description2_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='summary_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='summary_it',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='title_it',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
