# Generated by Django 3.1.3 on 2020-12-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20201216_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinfo',
            name='gallery',
        ),
    ]
