# Generated by Django 3.1.3 on 2020-12-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_remove_detailinfo_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info/detail/gallery')),
                ('detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.detailinfo')),
            ],
        ),
    ]
