# Generated by Django 3.1.3 on 2020-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='description2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='description2_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='description2_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
