# Generated by Django 3.1.3 on 2020-12-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_detailinfo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='menu_word',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='menu_word_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_word_it',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
