# Generated by Django 3.1.3 on 2020-12-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20201218_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailinfo',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_info', to='info.category'),
        ),
    ]
