# Generated by Django 3.1.3 on 2020-12-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20201219_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='desc_title1',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='desc_title2',
            field=models.CharField(default='', max_length=60),
        ),
    ]
