# Generated by Django 3.1.3 on 2020-12-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_auto_20201223_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='desc_title2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='desc_title2_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='desc_title2_it',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
