# Generated by Django 3.1.3 on 2020-12-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20201223_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='info.detailinfo'),
        ),
    ]
