# Generated by Django 3.1.3 on 2020-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20201223_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='bot_image',
            field=models.ImageField(blank=True, upload_to='info/detail'),
        ),
    ]
