# Generated by Django 3.1.3 on 2020-12-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_detailinfo_bot_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_it',
            new_name='title_it',
        ),
    ]
