# Generated by Django 3.1.3 on 2020-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20201224_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='theme',
            field=models.CharField(choices=[('secondary', 'beige'), ('info', 'blue'), ('brown', 'brown'), ('success', 'green'), ('primary', 'navy'), ('purple', 'purple'), ('danger', 'red'), ('warning', 'yellow')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='desc_image',
            field=models.ImageField(upload_to='info/detail'),
        ),
    ]
