# Generated by Django 3.1.3 on 2020-12-28 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_auto_20201225_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('title_en', models.CharField(max_length=60, null=True)),
                ('title_it', models.CharField(max_length=60, null=True)),
                ('summary', models.CharField(max_length=400)),
                ('summary_en', models.CharField(max_length=400, null=True)),
                ('summary_it', models.CharField(max_length=400, null=True)),
                ('desc_title1', models.CharField(max_length=60)),
                ('desc_title1_en', models.CharField(max_length=60, null=True)),
                ('desc_title1_it', models.CharField(max_length=60, null=True)),
                ('description1', models.TextField()),
                ('description1_en', models.TextField(null=True)),
                ('description1_it', models.TextField(null=True)),
                ('desc_title2', models.CharField(blank=True, default='', max_length=60)),
                ('desc_title2_en', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('desc_title2_it', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('description2', models.TextField(blank=True, default='')),
                ('description2_en', models.TextField(blank=True, default='', null=True)),
                ('description2_it', models.TextField(blank=True, default='', null=True)),
                ('title_image', models.ImageField(upload_to='info/page')),
                ('desc_image', models.ImageField(upload_to='info/page')),
                ('bot_image', models.ImageField(blank=True, upload_to='info/page')),
                ('order', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('theme', models.CharField(choices=[('secondary', 'beige'), ('info', 'blue'), ('brown', 'brown'), ('success', 'green'), ('primary', 'navy'), ('purple', 'purple'), ('danger', 'red'), ('warning', 'yellow')], default='info', max_length=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='info.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='detail',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='info/page/gallery'),
        ),
        migrations.DeleteModel(
            name='DetailInfo',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='info.page'),
        ),
    ]
