# Generated by Django 3.1.3 on 2020-12-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_auto_20201228_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='button_text',
            field=models.CharField(default='Learn More', max_length=30),
        ),
    ]
