# Generated by Django 3.1.3 on 2020-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_page_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='button_text_en',
            field=models.CharField(default='Learn More', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='button_text_it',
            field=models.CharField(default='Learn More', max_length=30, null=True),
        ),
    ]
