# Generated by Django 3.1.3 on 2021-01-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0032_auto_20201229_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.page'),
        ),
    ]
