# Generated by Django 3.1.3 on 2021-01-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_homecarousel_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.page'),
        ),
    ]
