# Generated by Django 3.1.3 on 2021-01-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_auto_20210101_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecarousel',
            old_name='image',
            new_name='image_big',
        ),
        migrations.RenameField(
            model_name='homecarousel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='homecarousel',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='homecarousel',
            old_name='name_it',
            new_name='title_it',
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='image_small',
            field=models.ImageField(default='', upload_to='carousel'),
            preserve_default=False,
        ),
    ]
