# Generated by Django 3.1.3 on 2021-01-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_auto_20210101_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCarousel',
            new_name='SplashImage',
        ),
    ]
