# Generated by Django 3.1.3 on 2021-01-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_auto_20210101_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splashimage',
            old_name='image_small',
            new_name='image_fb_link',
        ),
        migrations.RenameField(
            model_name='splashimage',
            old_name='image_big',
            new_name='image_tw_header',
        ),
    ]
