# Generated by Django 3.1.3 on 2021-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_auto_20210104_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_it',
            field=models.TextField(null=True),
        ),
    ]
