# Generated by Django 3.1.3 on 2021-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0038_auto_20210107_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_fb_link',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='bot_image',
            new_name='bot_image_tw_header',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='desc_image',
            new_name='image_fb_link',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_image',
            new_name='title_image_tw_header',
        ),
        migrations.RenameField(
            model_name='splashimage',
            old_name='display',
            new_name='info_display',
        ),
        migrations.AddField(
            model_name='splashimage',
            name='shop_display',
            field=models.BooleanField(default=False),
        ),
    ]
