# Generated by Django 3.1.3 on 2021-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0039_auto_20210213_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashimage',
            name='image_tw_header_md',
            field=models.ImageField(default='', upload_to='carousel'),
        ),
        migrations.AddField(
            model_name='splashimage',
            name='image_tw_header_sm',
            field=models.ImageField(default='', upload_to='carousel'),
        ),
    ]
