# Generated by Django 3.1.3 on 2021-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0040_auto_20210228_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashimage',
            name='image_fb_link_md',
            field=models.ImageField(default='', upload_to='carousel'),
        ),
        migrations.AddField(
            model_name='splashimage',
            name='image_fb_link_sm',
            field=models.ImageField(default='', upload_to='carousel'),
        ),
    ]
