# Generated by Django 3.1.3 on 2021-02-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0042_auto_20210228_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bot_image_tw_header_md',
            field=models.ImageField(blank=True, default='', upload_to='info/page/bot'),
        ),
        migrations.AddField(
            model_name='page',
            name='bot_image_tw_header_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/page/bot'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_fb_link_md',
            field=models.ImageField(default='', upload_to='info/page/desc'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_fb_link_sm',
            field=models.ImageField(default='', upload_to='info/page/desc'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_image_tw_header_md',
            field=models.ImageField(default='', upload_to='info/page/title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_image_tw_header_sm',
            field=models.ImageField(default='', upload_to='info/page/title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='bot_image_tw_header',
            field=models.ImageField(blank=True, upload_to='info/page/bot'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_fb_link',
            field=models.ImageField(upload_to='info/page/desc'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_image_tw_header',
            field=models.ImageField(upload_to='info/page/title'),
        ),
    ]
