# Generated by Django 3.1.3 on 2021-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0043_auto_20210228_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_fb_link_md',
            field=models.ImageField(blank=True, default='', upload_to='info/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_fb_link_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='bot_image_tw_header',
            field=models.ImageField(blank=True, default='', upload_to='info/page/bot'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_fb_link_md',
            field=models.ImageField(blank=True, default='', upload_to='info/page/desc'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_fb_link_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/page/desc'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_image_tw_header_md',
            field=models.ImageField(blank=True, default='', upload_to='info/page/title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_image_tw_header_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/page/title'),
        ),
        migrations.AlterField(
            model_name='splashimage',
            name='image_fb_link_md',
            field=models.ImageField(blank=True, default='', upload_to='info/carousel'),
        ),
        migrations.AlterField(
            model_name='splashimage',
            name='image_fb_link_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/carousel'),
        ),
        migrations.AlterField(
            model_name='splashimage',
            name='image_tw_header_md',
            field=models.ImageField(blank=True, default='', upload_to='info/carousel'),
        ),
        migrations.AlterField(
            model_name='splashimage',
            name='image_tw_header_sm',
            field=models.ImageField(blank=True, default='', upload_to='info/carousel'),
        ),
    ]
