# Generated by Django 3.1.3 on 2021-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0045_page_product_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='product_button_text_en',
            field=models.CharField(blank=True, default='Learn More', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='product_button_text_it',
            field=models.CharField(blank=True, default='Learn More', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
