# Generated by Django 3.1.3 on 2021-04-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210327_1933'),
        ('info', '0047_page_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashimage',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='splashimage',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.page'),
        ),
    ]
