# Generated by Django 3.1.8 on 2021-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0048_auto_20210403_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=30),
        ),
    ]
