# Generated by Django 3.1.8 on 2021-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0049_auto_20210503_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(default='', editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_it',
            field=models.SlugField(default='', editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(default='', editable=False, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_it',
            field=models.SlugField(default='', editable=False, max_length=60, null=True),
        ),
    ]
