# Generated by Django 3.1.8 on 2021-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0049_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=60),
        ),
    ]
