# Generated by Django 3.1.8 on 2021-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0050_auto_20210504_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
