# Generated by Django 3.1.8 on 2021-05-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0003_auto_20210511_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='', editable=False, max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consent', models.BooleanField(editable=False)),
                ('current_dialogue', models.TextField(default='', editable=False)),
                ('current_javascript', models.TextField(default='', editable=False)),
                ('cookie_policy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_policy', to='policies.policy')),
                ('privacy_policy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='policies.policy')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookierecord', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
