name: Production CI + Deploy

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup for python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install coveralls==2.2.0

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run DJango Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          DEVELOPMENT: True
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HEROKU_POSTGRESQL_CRIMSON_URL: ${{ secrets.HEROKU_POSTGRESQL_CRIMSON_URL }}
          COVERALLS_REPO: ${{ secrets.COVERALLS_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage run --source=. --omit=config/*,manage.py manage.py test --keepdb
          coveralls

  heroku_git_deploy_job:
    needs: build
    runs-on: ubuntu-latest
    name: Git Deploy job- A job to deploy django app to heroku using git
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy django to heroku
        uses: nyakaz73/heroku-django-deploy@v0.68
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email_address: ${{ secrets.HEROKU_EMAIL }}
