# Generated by Django 3.1.3 on 2021-01-04 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Shop Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', tinymce.models.HTMLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='shop/products')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.SmallIntegerField(default=1)),
                ('times_purchased', models.IntegerField(default=0, editable=False)),
                ('popularity', models.IntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.shopcategory')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
    ]
