# Generated by Django 3.1.3 on 2021-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
