# Generated by Django 3.1.3 on 2021-01-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shopcategory_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
