# Generated by Django 3.1.3 on 2021-01-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210107_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_4_3',
        ),
    ]
