# Generated by Django 3.1.3 on 2021-03-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210126_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_4_3_md',
            field=models.ImageField(blank=True, default='', upload_to='shop/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4_3_sm',
            field=models.ImageField(blank=True, default='', upload_to='shop/products'),
        ),
    ]
