# Generated by Django 3.1.3 on 2021-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210301_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4_3_xs',
            field=models.ImageField(blank=True, default='', upload_to='shop/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_artisanal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(default=10),
        ),
    ]
