# Generated by Django 3.1.3 on 2021-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210327_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
    ]
