# Generated by Django 3.1.8 on 2021-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='title_it',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
