# Generated by Django 3.1.8 on 2021-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210518_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.DecimalField(decimal_places=10, default=0, editable=False, max_digits=20),
        ),
    ]
