# Generated by Django 3.1.8 on 2021-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210518_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_4_3',
            field=models.ImageField(upload_to='shop/products'),
        ),
    ]
