# Generated by Django 3.1.8 on 2021-05-22 17:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210522_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_it',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
