# Generated by Django 3.1.8 on 2021-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210522_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=6.99, max_digits=10),
        ),
    ]
